/** Index and topic page generation — writes _index.md and _topics/{tag}.md. */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { RegistryBackend } from "../../storage/registry-interface.js";
import { fmtDate } from "../../cli/utils.js";
import { findNotesDir, findClaudeNotesDir } from "./symlinks.js";
import { paiHomePath, resolvePaiFile, migratePaiDir, type MigrateDirResult } from "../../config/pai-home.js";

/**
 * Generate _index.md listing all projects with session counts, tags, and
 * indicators for which note sources are available (notes, sessions, or both).
 */
export async function generateIndex(vaultPath: string, registry: RegistryBackend): Promise<void> {
  mkdirSync(vaultPath, { recursive: true });

  const rows = await registry.listProjectsWithSessionStats();

  const active = rows.filter((r) => r.status === "active");
  const archived = rows.filter((r) => r.status !== "active");

  const lines: string[] = [
    "# PAI Project Index",
    "",
    `> Auto-generated by PAI Knowledge OS — ${new Date().toISOString()}`,
    "",
    "## Active Projects",
    "",
    "| Project | Sessions | Last Active | Sources | Tags |",
    "| ------- | -------- | ----------- | ------- | ---- |",
  ];

  for (const row of active) {
    const tags = (await registry.listTagsForProject(row.id)).map((t) => `\`${t}\``).join(" ");
    const lastActive = fmtDate(row.last_active);

    const notesDir = findNotesDir(row.root_path);
    const claudeNotesDir = findClaudeNotesDir(row.claude_notes_dir, notesDir);
    const sources: string[] = [];
    if (notesDir) sources.push("notes");
    if (claudeNotesDir) sources.push("sessions");
    const sourcesLabel = sources.length > 0 ? sources.join(", ") : "—";

    lines.push(
      `| [[${row.slug}/|${row.display_name}]] | ${row.session_count} | ${lastActive} | ${sourcesLabel} | ${tags || "—"} |`
    );
  }

  if (archived.length > 0) {
    lines.push(
      "",
      "## Archived Projects",
      "",
      "| Project | Sessions | Tags |",
      "| ------- | -------- | ---- |"
    );
    for (const row of archived) {
      const tags = (await registry.listTagsForProject(row.id)).map((t) => `\`${t}\``).join(" ");
      lines.push(
        `| [${row.display_name}](_archive/${row.slug}.md) | ${row.session_count} | ${tags || "—"} |`
      );
    }
  }

  lines.push(
    "",
    "---",
    `*${rows.length} projects total — ${active.length} active, ${archived.length} archived*`
  );

  writeFileSync(join(vaultPath, "_index.md"), lines.join("\n") + "\n", "utf-8");
}

/**
 * Generate per-tag topic pages at _topics/{tag}.md.
 * Returns count of pages written.
 */
export async function generateTopicPages(vaultPath: string, registry: RegistryBackend): Promise<number> {
  const topicsDir = join(vaultPath, "_topics");
  mkdirSync(topicsDir, { recursive: true });

  const allTags = await registry.listAllTags();

  let written = 0;
  for (const tag of allTags) {
    const projects = await registry.listProjectsWithSessionStats({ tagId: tag.id });
    if (!projects.length) continue;

    const lines: string[] = [
      `# Topic: ${tag.name}`,
      "",
      `> Auto-generated by PAI Knowledge OS — ${new Date().toISOString()}`,
      "",
      "## Projects",
      "",
      "| Project | Status | Sessions | Last Active |",
      "| ------- | ------ | -------- | ----------- |",
    ];

    for (const p of projects) {
      const link =
        p.status === "active"
          ? `[[${p.slug}/|${p.display_name}]]`
          : `[${p.display_name}](../_archive/${p.slug}.md)`;
      lines.push(`| ${link} | ${p.status} | ${p.session_count} | ${fmtDate(p.last_active)} |`);
    }

    lines.push("", "---", `*${projects.length} project(s) tagged \`${tag.name}\`*`);

    writeFileSync(join(topicsDir, `${tag.name}.md`), lines.join("\n") + "\n", "utf-8");
    written++;
  }

  return written;
}

/** Old default vault path, inside ~/.pai/ (pre-2026-09-19). */
export function oldDefaultVaultPath(): string {
  return join(homedir(), ".pai", "obsidian-vault");
}

/**
 * Default vault path: PAI_HOME/obsidian-vault if present, else the old
 * ~/.pai/obsidian-vault (one-time stderr notice), else the new path.
 */
export function defaultVaultPath(): string {
  return resolvePaiFile(paiHomePath("obsidian-vault"), [oldDefaultVaultPath()], "pai config migrate --obsidian-vault");
}

export function migrateObsidianVaultDir(opts: { dryRun?: boolean } = {}): MigrateDirResult {
  return migratePaiDir(paiHomePath("obsidian-vault"), [oldDefaultVaultPath()], opts);
}
