/** Index and topic page generation — writes _index.md and _topics/{tag}.md. */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import type { Database } from "better-sqlite3";
import { fmtDate } from "../../cli/utils.js";
import type { ProjectRow, SessionStats, TagRow } from "./types.js";
import { findNotesDir, findClaudeNotesDir } from "./symlinks.js";

/**
 * Generate _index.md listing all projects with session counts, tags, and
 * indicators for which note sources are available (notes, sessions, or both).
 */
export function generateIndex(vaultPath: string, db: Database): void {
  mkdirSync(vaultPath, { recursive: true });

  const rows = db
    .prepare(
      `SELECT p.id, p.slug, p.display_name, p.status, p.root_path,
         p.encoded_dir, p.claude_notes_dir,
         (SELECT COUNT(*) FROM sessions s WHERE s.project_id = p.id) AS session_count,
         (SELECT MAX(s.created_at) FROM sessions s WHERE s.project_id = p.id) AS last_active
       FROM projects p
       ORDER BY p.status ASC, p.updated_at DESC`
    )
    .all() as (ProjectRow & SessionStats)[];

  const getTagsForProject = db.prepare(
    `SELECT t.name FROM tags t
     JOIN project_tags pt ON pt.tag_id = t.id
     WHERE pt.project_id = ?
     ORDER BY t.name`
  );

  const active = rows.filter((r) => r.status === "active");
  const archived = rows.filter((r) => r.status !== "active");

  const lines: string[] = [
    "# PAI Project Index",
    "",
    `> Auto-generated by PAI Knowledge OS — ${new Date().toISOString()}`,
    "",
    "## Active Projects",
    "",
    "| Project | Sessions | Last Active | Sources | Tags |",
    "| ------- | -------- | ----------- | ------- | ---- |",
  ];

  for (const row of active) {
    const tags = (getTagsForProject.all(row.id) as TagRow[]).map((t) => `\`${t.name}\``).join(" ");
    const lastActive = fmtDate(row.last_active);

    const notesDir = findNotesDir(row.root_path);
    const claudeNotesDir = findClaudeNotesDir(row.claude_notes_dir, notesDir);
    const sources: string[] = [];
    if (notesDir) sources.push("notes");
    if (claudeNotesDir) sources.push("sessions");
    const sourcesLabel = sources.length > 0 ? sources.join(", ") : "—";

    lines.push(
      `| [[${row.slug}/|${row.display_name}]] | ${row.session_count} | ${lastActive} | ${sourcesLabel} | ${tags || "—"} |`
    );
  }

  if (archived.length > 0) {
    lines.push(
      "",
      "## Archived Projects",
      "",
      "| Project | Sessions | Tags |",
      "| ------- | -------- | ---- |"
    );
    for (const row of archived) {
      const tags = (getTagsForProject.all(row.id) as TagRow[]).map((t) => `\`${t.name}\``).join(" ");
      lines.push(
        `| [${row.display_name}](_archive/${row.slug}.md) | ${row.session_count} | ${tags || "—"} |`
      );
    }
  }

  lines.push(
    "",
    "---",
    `*${rows.length} projects total — ${active.length} active, ${archived.length} archived*`
  );

  writeFileSync(join(vaultPath, "_index.md"), lines.join("\n") + "\n", "utf-8");
}

/**
 * Generate per-tag topic pages at _topics/{tag}.md.
 * Returns count of pages written.
 */
export function generateTopicPages(vaultPath: string, db: Database): number {
  const topicsDir = join(vaultPath, "_topics");
  mkdirSync(topicsDir, { recursive: true });

  const allTags = db
    .prepare("SELECT id, name FROM tags ORDER BY name")
    .all() as { id: number; name: string }[];

  const getProjectsForTag = db.prepare(
    `SELECT p.id, p.slug, p.display_name, p.status,
       (SELECT COUNT(*) FROM sessions s WHERE s.project_id = p.id) AS session_count,
       (SELECT MAX(s.created_at) FROM sessions s WHERE s.project_id = p.id) AS last_active
     FROM projects p
     JOIN project_tags pt ON pt.project_id = p.id
     WHERE pt.tag_id = ?
     ORDER BY p.status ASC, p.updated_at DESC`
  );

  let written = 0;
  for (const tag of allTags) {
    const projects = getProjectsForTag.all(tag.id) as (ProjectRow & SessionStats)[];
    if (!projects.length) continue;

    const lines: string[] = [
      `# Topic: ${tag.name}`,
      "",
      `> Auto-generated by PAI Knowledge OS — ${new Date().toISOString()}`,
      "",
      "## Projects",
      "",
      "| Project | Status | Sessions | Last Active |",
      "| ------- | ------ | -------- | ----------- |",
    ];

    for (const p of projects) {
      const link =
        p.status === "active"
          ? `[[${p.slug}/|${p.display_name}]]`
          : `[${p.display_name}](../_archive/${p.slug}.md)`;
      lines.push(`| ${link} | ${p.status} | ${p.session_count} | ${fmtDate(p.last_active)} |`);
    }

    lines.push("", "---", `*${projects.length} project(s) tagged \`${tag.name}\`*`);

    writeFileSync(join(topicsDir, `${tag.name}.md`), lines.join("\n") + "\n", "utf-8");
    written++;
  }

  return written;
}

/**
 * Default vault path: ~/.pai/obsidian-vault
 */
export function defaultVaultPath(): string {
  return join(homedir(), ".pai", "obsidian-vault");
}
