/** Master note generation and session tag fixing for vault projects. */

import {
  existsSync,
  unlinkSync,
  writeFileSync,
  readFileSync,
} from "node:fs";
import { join } from "node:path";
import type { Database } from "better-sqlite3";
import type { ProjectRow } from "./types.js";
import { collectSessionFiles, walkNotesDir } from "./walk.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build the per-project master note filename. */
export function masterFilename(slug: string): string {
  return `_${slug}-master.md`;
}

/**
 * Remove any old/broken backlink footer from a session file.
 * Returns true if the file was modified.
 */
function removeOldBacklink(filePath: string): boolean {
  let content: string;
  try {
    content = readFileSync(filePath, "utf-8");
  } catch {
    return false;
  }
  const oldPattern = /\n---\n\[\[\.\.\/[^\]]+\]\]\n?$/;
  const newPattern = /\n---\n\[\[_[^\]]*-master\|[^\]]*\]\]\n?$/;
  const cleaned = content.replace(oldPattern, "").replace(newPattern, "");
  if (cleaned === content) return false;
  try {
    writeFileSync(filePath, cleaned, "utf-8");
    return true;
  } catch {
    return false;
  }
}

/**
 * Append the master note backlink footer to a session file, idempotently.
 * Only writes if the sentinel string is not already present.
 */
function appendBacklinkIfMissing(
  filePath: string,
  slug: string,
  displayName: string
): boolean {
  let content: string;
  try {
    content = readFileSync(filePath, "utf-8");
  } catch {
    return false;
  }
  const masterName = masterFilename(slug).replace(/\.md$/, "");
  const sentinel = `[[${masterName}|`;
  if (content.includes(sentinel)) return false;

  const footer = `\n---\n[[${masterName}|← ${displayName} Master]]\n`;
  try {
    writeFileSync(filePath, content + footer, "utf-8");
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Public: generateMasterNotes
// ---------------------------------------------------------------------------

/**
 * Generate _master.md files for projects that have >= threshold session files.
 *
 * For each qualifying project, writes a {vaultPath}/{slug}/_master.md containing:
 *   - Project title, session count + date range
 *   - Sessions grouped by YYYY/MM with Obsidian [[wikilinks]]
 *
 * Also appends a backlink footer to each session file (idempotently).
 *
 * @param vaultPath  Absolute path to the PAI Obsidian vault
 * @param db         Registry SQLite database
 * @param threshold  Minimum session count to generate a master note (default: 5)
 * @returns          Number of master notes written
 */
export function generateMasterNotes(
  vaultPath: string,
  db: Database,
  threshold = 5
): number {
  if (!existsSync(vaultPath)) return 0;

  const projects = db
    .prepare(
      `SELECT id, slug, display_name, root_path, encoded_dir, status, obsidian_link, claude_notes_dir
       FROM projects
       WHERE status = 'active'
       ORDER BY slug ASC`
    )
    .all() as ProjectRow[];

  let written = 0;

  for (const project of projects) {
    const slugPath = join(vaultPath, project.slug);
    if (!existsSync(slugPath)) continue;

    // Remove legacy _master.md if present
    const legacyMaster = join(slugPath, "_master.md");
    if (existsSync(legacyMaster)) {
      try { unlinkSync(legacyMaster); } catch { /* Non-fatal */ }
    }

    const sessionFiles = collectSessionFiles(slugPath);
    if (sessionFiles.length < threshold) continue;

    // Sort by yearMonth then basename
    sessionFiles.sort((a, b) => {
      if (a.yearMonth !== b.yearMonth) return a.yearMonth.localeCompare(b.yearMonth);
      return a.basename.localeCompare(b.basename);
    });

    const byMonth = new Map<string, typeof sessionFiles>();
    for (const sf of sessionFiles) {
      if (!byMonth.has(sf.yearMonth)) byMonth.set(sf.yearMonth, []);
      byMonth.get(sf.yearMonth)!.push(sf);
    }

    const firstDate = sessionFiles[0]?.basename.match(/\d{4}-\d{2}-\d{2}/)?.[0] ?? "unknown";
    const lastDate = sessionFiles[sessionFiles.length - 1]?.basename.match(/\d{4}-\d{2}-\d{2}/)?.[0] ?? "unknown";

    const lines: string[] = [
      `# Project: ${project.display_name}`,
      "",
      `> Auto-generated by PAI Knowledge OS — ${new Date().toISOString()}`,
      "",
      "## Overview",
      "",
      `- **Sessions:** ${sessionFiles.length}`,
      `- **Date range:** ${firstDate} to ${lastDate}`,
      `- **Tags:** #${project.slug} #project`,
      "",
      "## Sessions by Month",
      "",
    ];

    for (const [ym, files] of byMonth) {
      lines.push(`### ${ym}`, "");
      for (const sf of files) {
        lines.push(`- [[${sf.wikilinkTarget}|${sf.basename}]]`);
      }
      lines.push("");
    }

    lines.push("## Topics", "", `#${project.slug} #project`, "");

    const masterPath = join(slugPath, masterFilename(project.slug));
    try {
      writeFileSync(masterPath, lines.join("\n"), "utf-8");
      written++;
    } catch {
      continue;
    }

    for (const sf of sessionFiles) {
      removeOldBacklink(sf.absPath);
      appendBacklinkIfMissing(sf.absPath, project.slug, project.display_name);
    }
  }

  return written;
}

// ---------------------------------------------------------------------------
// Public: fixSessionTags
// ---------------------------------------------------------------------------

/**
 * Remove the generic #Session tag from session note files across all projects.
 *
 * Scans all session and notes directories for every active project and removes
 * #Session (with or without a trailing space) from any `**Tags:**` line.
 *
 * @param db  Registry SQLite database
 * @returns   Object with counts: { filesScanned, filesModified, errors }
 */
export function fixSessionTags(
  db: Database
): { filesScanned: number; filesModified: number; errors: string[] } {
  const results = { filesScanned: 0, filesModified: 0, errors: [] as string[] };

  const projects = db
    .prepare(
      `SELECT id, slug, display_name, root_path, encoded_dir, status, obsidian_link, claude_notes_dir
       FROM projects
       WHERE status = 'active'
       ORDER BY slug ASC`
    )
    .all() as ProjectRow[];

  for (const project of projects) {
    const dirsToScan: string[] = [];

    // Inline findNotesDir to avoid a circular dependency with symlinks.ts
    const canonical = join(project.root_path, "Notes");
    const alt = join(project.root_path, ".claude", "Notes");
    const notesDir = existsSync(canonical) ? canonical : existsSync(alt) ? alt : null;

    if (notesDir) dirsToScan.push(notesDir);

    if (
      project.claude_notes_dir &&
      existsSync(project.claude_notes_dir) &&
      project.claude_notes_dir !== notesDir
    ) {
      dirsToScan.push(project.claude_notes_dir);
    }

    for (const dir of dirsToScan) {
      const files = walkNotesDir(dir);
      for (const filePath of files) {
        results.filesScanned++;
        let content: string;
        try {
          content = readFileSync(filePath, "utf-8");
        } catch (e) {
          results.errors.push(`${filePath}: read error — ${e}`);
          continue;
        }

        if (!content.includes("#Session")) continue;

        const updated = content.replace(
          /(\*\*Tags:\*\*[^\n]*)#Session ?/g,
          "$1"
        );

        if (updated === content) continue;

        const cleaned = updated.replace(/(\*\*Tags:\*\*) *\n/g, "$1\n");

        try {
          writeFileSync(filePath, cleaned, "utf-8");
          results.filesModified++;
        } catch (e) {
          results.errors.push(`${filePath}: write error — ${e}`);
        }
      }
    }
  }

  return results;
}
