/**
 * Shim — re-exports from project-utils/ directory so existing importers
 * continue to work without modification. See project-utils/index.ts.
 */
export type { WorkItem, TodoItem } from "./project-utils/index.js";
export {
  PAI_DIR,
  PROJECTS_DIR,
  isProbeSession,
  encodePath,
  getProjectDir,
  getNotesDir,
  findNotesDir,
  getSessionsDir,
  getSessionsDirFromProjectDir,
  ensureNotesDir,
  ensureNotesDirSmart,
  ensureSessionsDir,
  ensureSessionsDirFromProjectDir,
  moveSessionFilesToSessionsDir,
  findTodoPath,
  findClaudeMdPath,
  findAllClaudeMdPaths,
  isWhatsAppEnabled,
  sendNtfyNotification,
  getNextNoteNumber,
  getCurrentNotePath,
  createSessionNote,
  appendCheckpoint,
  addWorkToSessionNote,
  sanitizeForFilename,
  extractMeaningfulName,
  renameSessionNote,
  updateSessionNoteTitle,
  finalizeSessionNote,
  calculateSessionTokens,
  ensureTodoMd,
  updateTodoMd,
  addTodoCheckpoint,
  updateTodoContinue,
} from "./project-utils/index.js";
