/** Step 4: CLAUDE.md generation from PAI template. */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import chalk from "chalk";
import { CONFIG_DIR } from "../../../../daemon/config.js";
import { c, line, section, type Rl, promptYesNo, getTemplatesDir } from "../utils.js";

export async function stepClaudeMd(rl: Rl): Promise<boolean> {
  section("Step 4: Agent Configuration (CLAUDE.md)");
  line();
  line("  PAI ships a CLAUDE.md template with agent orchestration patterns:");
  line("  swarm mode, model escalation, parallel execution, quality standards.");
  line();

  const claudeDir = join(homedir(), ".claude");
  const claudeMd = join(claudeDir, "CLAUDE.md");
  const agentPrefs = join(CONFIG_DIR, "agent-prefs.md");
  const templatesDir = getTemplatesDir();
  const templatePath = join(templatesDir, "claude-md.template.md");

  if (!existsSync(templatePath)) {
    console.log(c.warn("Template not found: " + templatePath));
    console.log(c.dim("  Skipping CLAUDE.md generation. You can copy it manually from templates/."));
    return false;
  }

  if (existsSync(claudeMd)) {
    const content = readFileSync(claudeMd, "utf-8");
    const isGenerated = content.includes("Generated by PAI Setup");
    if (isGenerated) {
      console.log(c.dim("  Found existing PAI-generated CLAUDE.md."));
    } else {
      console.log(c.yellow("  Found existing CLAUDE.md (custom, not PAI-generated)."));
      console.log(c.dim("  A backup will be created before overwriting."));
    }
    line();

    const overwrite = await promptYesNo(rl, "Update ~/.claude/CLAUDE.md with the latest PAI template?", isGenerated);
    if (!overwrite) {
      console.log(c.dim("  Keeping existing CLAUDE.md unchanged."));
      return false;
    }

    if (!isGenerated) {
      const backupPath = claudeMd + ".backup";
      writeFileSync(backupPath, content, "utf-8");
      console.log(c.ok(`Backed up existing CLAUDE.md to ${backupPath}`));
    }
  }

  let template = readFileSync(templatePath, "utf-8");
  template = template.replace(/\$\{HOME\}/g, homedir());

  if (!existsSync(claudeDir)) {
    mkdirSync(claudeDir, { recursive: true });
  }
  writeFileSync(claudeMd, template, "utf-8");

  line();
  console.log(c.ok("Generated ~/.claude/CLAUDE.md from PAI template."));

  if (!existsSync(agentPrefs)) {
    line();
    line("  For personal settings (project mappings, notification preferences),");
    line("  copy the example and customize:");
    line();
    console.log(chalk.cyan(`    cp ${templatesDir}/agent-prefs.example.md ${agentPrefs}`));
    line();

    const createPrefs = await promptYesNo(rl, "Copy the example agent-prefs.md now?", true);
    if (createPrefs) {
      const examplePath = join(templatesDir, "agent-prefs.example.md");
      if (existsSync(examplePath)) {
        if (!existsSync(CONFIG_DIR)) {
          mkdirSync(CONFIG_DIR, { recursive: true });
        }
        writeFileSync(agentPrefs, readFileSync(examplePath, "utf-8"), "utf-8");
        console.log(c.ok(`Created ${agentPrefs}`));
        console.log(c.dim("  Edit this file to add your personal preferences and project mappings."));
      } else {
        console.log(c.warn("Example file not found. Create agent-prefs.md manually."));
      }
    }
  } else {
    console.log(c.dim("  Personal preferences: " + agentPrefs));
  }

  return true;
}
