/** Step 5: PAI SKILL.md installation to ~/.claude/skills/PAI/. */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { c, line, section, type Rl, promptYesNo, getTemplatesDir } from "../utils.js";

export async function stepPaiSkill(rl: Rl): Promise<boolean> {
  section("Step 5: PAI Skill Installation");
  line();
  line("  PAI ships a SKILL.md that tells Claude Code how to invoke PAI commands.");
  line();

  const templatesDir = getTemplatesDir();
  const templatePath = join(templatesDir, "pai-skill.template.md");

  if (!existsSync(templatePath)) {
    console.log(c.warn("Skill template not found: " + templatePath));
    console.log(c.dim("  Skipping PAI skill installation."));
    return false;
  }

  const skillDir = join(homedir(), ".claude", "skills", "PAI");
  const skillFile = join(skillDir, "SKILL.md");

  if (existsSync(skillFile)) {
    const content = readFileSync(skillFile, "utf-8");
    const isGenerated = content.includes("Generated by PAI Setup");
    if (isGenerated) {
      console.log(c.dim("  Found existing PAI-generated SKILL.md."));
    } else {
      console.log(c.yellow("  Found existing SKILL.md (not PAI-generated)."));
      console.log(c.dim("  A backup will be created before overwriting."));
    }
    line();

    const overwrite = await promptYesNo(rl, "Update ~/.claude/skills/PAI/SKILL.md with the latest PAI skill?", isGenerated);
    if (!overwrite) {
      console.log(c.dim("  Keeping existing SKILL.md unchanged."));
      return false;
    }

    if (!isGenerated) {
      const backupPath = skillFile + ".backup";
      writeFileSync(backupPath, content, "utf-8");
      console.log(c.ok(`Backed up existing SKILL.md to ${backupPath}`));
    }
  } else {
    const install = await promptYesNo(rl, "Install PAI skill to ~/.claude/skills/PAI/SKILL.md?", true);
    if (!install) {
      console.log(c.dim("  Skipping PAI skill installation."));
      return false;
    }
  }

  let template = readFileSync(templatePath, "utf-8");
  template = template.replace(/\$\{HOME\}/g, homedir());

  if (!existsSync(skillDir)) {
    mkdirSync(skillDir, { recursive: true });
  }
  writeFileSync(skillFile, template, "utf-8");

  line();
  console.log(c.ok("Installed ~/.claude/skills/PAI/SKILL.md"));
  return true;
}
