/** Step 6: AI Steering Rules installation to ~/.claude/skills/PAI/. */

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { c, line, section, type Rl, promptYesNo, getTemplatesDir } from "../utils.js";

export async function stepAiSteeringRules(rl: Rl): Promise<boolean> {
  section("Step 6: AI Steering Rules");
  line();
  line("  PAI ships a set of universal behavioral rules for AI assistants:");
  line("  surgical fixes, verification before assertion, root cause analysis,");
  line("  and honest failure modes. These rules load at startup as a skill.");
  line();

  const templatesDir = getTemplatesDir();
  const templatePath = join(templatesDir, "ai-steering-rules.template.md");

  if (!existsSync(templatePath)) {
    console.log(c.warn("AI steering rules template not found: " + templatePath));
    console.log(c.dim("  Skipping AI steering rules installation."));
    return false;
  }

  const skillDir = join(homedir(), ".claude", "skills", "PAI");
  const skillFile = join(skillDir, "AI-STEERING-RULES.md");

  if (existsSync(skillFile)) {
    const content = readFileSync(skillFile, "utf-8");
    const isGenerated = content.includes("Generated by PAI Setup");
    if (isGenerated) {
      console.log(c.dim("  Found existing PAI-generated AI-STEERING-RULES.md."));
    } else {
      console.log(c.yellow("  Found existing AI-STEERING-RULES.md (not PAI-generated)."));
      console.log(c.dim("  A backup will be created before overwriting."));
    }
    line();

    const overwrite = await promptYesNo(rl, "Update ~/.claude/skills/PAI/AI-STEERING-RULES.md with the latest rules?", isGenerated);
    if (!overwrite) {
      console.log(c.dim("  Keeping existing AI-STEERING-RULES.md unchanged."));
      return false;
    }

    if (!isGenerated) {
      const backupPath = skillFile + ".backup";
      writeFileSync(backupPath, content, "utf-8");
      console.log(c.ok(`Backed up existing AI-STEERING-RULES.md to ${backupPath}`));
    }
  } else {
    const install = await promptYesNo(rl, "Install AI steering rules to ~/.claude/skills/PAI/AI-STEERING-RULES.md?", true);
    if (!install) {
      console.log(c.dim("  Skipping AI steering rules installation."));
      return false;
    }
  }

  const template = readFileSync(templatePath, "utf-8");

  if (!existsSync(skillDir)) {
    mkdirSync(skillDir, { recursive: true });
  }
  writeFileSync(skillFile, template, "utf-8");

  line();
  console.log(c.ok("Installed ~/.claude/skills/PAI/AI-STEERING-RULES.md"));
  return true;
}
