#!/usr/bin/env node
/**
 * Generate per-area command reference ("man pages") from the live Commander tree.
 *
 * Source of truth: src/cli/program.ts → buildProgram(). We import the BUILT
 * program (dist/cli/program.mjs), introspect every visible command, and emit:
 *
 *   docs/commands/<area>.md   — one man page per top-level command area
 *   docs/commands/README.md   — index (area table + flat apropos list)
 *
 * Curated EXAMPLES are spliced in from docs/commands/_examples/<area>.md when
 * present (hand-written, the only part that isn't generated).
 *
 * Never edit the generated files by hand — they are overwritten on every build.
 * Run automatically during `bun run build`.
 */

import {
  writeFileSync,
  mkdirSync,
  existsSync,
  readFileSync,
  readdirSync,
  rmSync,
} from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "docs", "commands");
const EXAMPLES_DIR = join(OUT_DIR, "_examples");
const PROGRAM_MJS = join(ROOT, "dist", "cli", "program.mjs");

const GEN_HEADER =
  "<!-- GENERATED by scripts/build-docs.mjs from the live Commander tree (src/cli/program.ts). Do not edit by hand. -->";

// ---------------------------------------------------------------------------
// Commander introspection helpers (defensive against minor version drift)
// ---------------------------------------------------------------------------

function isHidden(cmd) {
  return Boolean(cmd._hidden);
}

function cmdName(cmd) {
  return cmd.name();
}

function cmdAliases(cmd) {
  try {
    return cmd.aliases() ?? [];
  } catch {
    return [];
  }
}

function cmdDescription(cmd) {
  try {
    return cmd.description() ?? "";
  } catch {
    return "";
  }
}

function getArguments(cmd) {
  const args = cmd.registeredArguments ?? cmd._args ?? [];
  return args.map((a) => ({
    name: typeof a.name === "function" ? a.name() : a._name,
    required: Boolean(a.required),
    variadic: Boolean(a.variadic),
    description: a.description ?? "",
  }));
}

function getOptions(cmd) {
  return (cmd.options ?? [])
    .filter((o) => !o.hidden)
    .map((o) => ({
      flags: o.flags,
      description: o.description ?? "",
      defaultValue: o.defaultValue,
    }));
}

function visibleSubcommands(cmd) {
  return (cmd.commands ?? []).filter((c) => !isHidden(c));
}

// ---------------------------------------------------------------------------
// Markdown helpers
// ---------------------------------------------------------------------------

function esc(s) {
  return String(s ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function firstLine(s) {
  return String(s ?? "").split("\n")[0].trim();
}

function restLines(s) {
  const lines = String(s ?? "").split("\n");
  return lines.slice(1).join("\n").trim();
}

function argToken(a) {
  const base = a.variadic ? `${a.name}...` : a.name;
  return a.required ? `<${base}>` : `[${base}]`;
}

function argString(cmd) {
  const args = getArguments(cmd);
  return args.map(argToken).join(" ");
}

function anchor(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

function defaultCell(v) {
  if (v === undefined || v === null) return "";
  if (typeof v === "boolean") return v ? "`true`" : "";
  return `\`${esc(v)}\``;
}

function optionsTable(opts) {
  if (opts.length === 0) return "";
  const rows = opts
    .map((o) => `| \`${esc(o.flags)}\` | ${esc(o.description)} | ${defaultCell(o.defaultValue)} |`)
    .join("\n");
  return `| Option | Description | Default |\n|--------|-------------|---------|\n${rows}\n`;
}

function argumentsTable(cmd) {
  const args = getArguments(cmd);
  if (args.length === 0) return "";
  const kindOf = (a) => (a.variadic ? "variadic" : a.required ? "required" : "optional");
  const anyDesc = args.some((a) => esc(a.description) !== "");

  if (!anyDesc) {
    const rows = args.map((a) => `| \`${esc(argToken(a))}\` | ${kindOf(a)} |`).join("\n");
    return `| Argument | Kind |\n|----------|------|\n${rows}\n`;
  }

  const rows = args
    .map((a) => `| \`${esc(argToken(a))}\` | ${kindOf(a)} | ${esc(a.description)} |`)
    .join("\n");
  return `| Argument | Kind | Description |\n|----------|------|-------------|\n${rows}\n`;
}

function loadExamples(area) {
  const p = join(EXAMPLES_DIR, `${area}.md`);
  if (!existsSync(p)) return "";
  return readFileSync(p, "utf8").trim();
}

// ---------------------------------------------------------------------------
// Page rendering
// ---------------------------------------------------------------------------

function renderSubcommandDetail(parentPath, sub) {
  const name = cmdName(sub);
  const argStr = argString(sub);
  const heading = `pai ${parentPath} ${name}${argStr ? " " + argStr : ""}`.trim();
  const out = [`### ${heading}`, ""];

  const desc = cmdDescription(sub);
  if (desc) {
    out.push(firstLine(desc));
    const rest = restLines(desc);
    if (rest) out.push("", rest);
    out.push("");
  }

  const aliases = cmdAliases(sub);
  if (aliases.length > 0) {
    out.push(`*Aliases:* ${aliases.map((a) => `\`${a}\``).join(", ")}`, "");
  }

  const argTable = argumentsTable(sub);
  if (argTable) {
    out.push("**Arguments**", "", argTable);
  }

  const opts = getOptions(sub);
  if (opts.length > 0) {
    out.push("**Options**", "", optionsTable(opts));
  }

  return out.join("\n");
}

function renderAreaPage(area, allAreas) {
  const name = cmdName(area);
  const subs = visibleSubcommands(area);
  const ownOpts = getOptions(area);
  const ownArgs = argString(area);
  const desc = cmdDescription(area);

  const out = [GEN_HEADER, "", `# pai ${name}`, ""];

  if (desc) {
    out.push(`> ${firstLine(desc)}`, "");
    const rest = restLines(desc);
    if (rest) out.push(rest, "");
  }

  const aliases = cmdAliases(area);
  if (aliases.length > 0) {
    out.push(`**Aliases:** ${aliases.map((a) => `\`${a}\``).join(", ")}`, "");
  }

  // Synopsis
  out.push("## Synopsis", "", "```");
  if (subs.length > 0) {
    out.push(`pai ${name} <subcommand> [options]`);
  }
  if (ownArgs || ownOpts.length > 0 || subs.length === 0) {
    out.push(`pai ${name}${ownArgs ? " " + ownArgs : ""}${ownOpts.length > 0 ? " [options]" : ""}`.trim());
  }
  out.push("```", "");

  // Own arguments
  const ownArgTable = argumentsTable(area);
  if (ownArgTable) {
    out.push("## Arguments", "", ownArgTable);
  }

  // Own options
  if (ownOpts.length > 0) {
    out.push("## Options", "", optionsTable(ownOpts));
  }

  // Subcommands table
  if (subs.length > 0) {
    out.push("## Subcommands", "");
    out.push("| Command | Description |", "|---------|-------------|");
    for (const sub of subs) {
      const subName = cmdName(sub);
      const argStr = argString(sub);
      const label = `pai ${name} ${subName}${argStr ? " " + argStr : ""}`.trim();
      const link = `#${anchor(`pai ${name} ${subName} ${argStr}`)}`;
      out.push(`| [\`${label}\`](${link}) | ${esc(firstLine(cmdDescription(sub)))} |`);
    }
    out.push("");

    // Per-subcommand detail
    for (const sub of subs) {
      out.push(renderSubcommandDetail(name, sub), "");
      // One level of nested subcommands (e.g. pai notes list)
      for (const nested of visibleSubcommands(sub)) {
        out.push(renderSubcommandDetail(`${name} ${cmdName(sub)}`, nested), "");
      }
    }
  }

  // Examples (curated, spliced in)
  const examples = loadExamples(name);
  if (examples) {
    out.push("## Examples", "", examples, "");
  }

  // See also
  const others = allAreas.filter((a) => a !== name);
  out.push("## See also", "");
  out.push(
    others.map((a) => `[\`pai ${a}\`](${a}.md)`).join(" · "),
    "",
    `Run \`pai help <area>\` to read any of these in the terminal.`,
    ""
  );

  return out.join("\n");
}

function flattenCommands(cmd, prefix, acc) {
  for (const sub of visibleSubcommands(cmd)) {
    const name = cmdName(sub);
    const argStr = argString(sub);
    const full = `${prefix} ${name}${argStr ? " " + argStr : ""}`.trim();
    acc.push({ command: full, description: firstLine(cmdDescription(sub)) });
    flattenCommands(sub, `${prefix} ${name}`, acc);
  }
}

function renderIndex(areas, program) {
  const out = [GEN_HEADER, "", "# PAI Command Reference", ""];
  out.push(
    "Generated man pages for every `pai` command area. Read any page in the terminal with `pai help <area>`, or browse the files here.",
    ""
  );

  // Area table
  out.push("## Areas", "");
  out.push("| Area | Description |", "|------|-------------|");
  for (const area of areas) {
    const name = cmdName(area);
    out.push(`| [\`pai ${name}\`](${name}.md) | ${esc(firstLine(cmdDescription(area)))} |`);
  }
  out.push("");

  // Apropos — flat alphabetical list of every visible command
  const flat = [];
  for (const area of areas) {
    const name = cmdName(area);
    flat.push({ command: `pai ${name}`, description: firstLine(cmdDescription(area)) });
    flattenCommands(area, `pai ${name}`, flat);
  }
  flat.sort((a, b) => a.command.localeCompare(b.command));

  out.push("## All commands", "");
  out.push("| Command | Description |", "|---------|-------------|");
  for (const c of flat) {
    out.push(`| \`${esc(c.command)}\` | ${esc(c.description)} |`);
  }
  out.push("");

  return out.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  if (!existsSync(PROGRAM_MJS)) {
    console.error(`✖ ${PROGRAM_MJS} not found — run tsdown first.`);
    process.exit(1);
  }

  const mod = await import(pathToFileURL(PROGRAM_MJS).href);
  if (typeof mod.buildProgram !== "function") {
    console.error("✖ dist/cli/program.mjs does not export buildProgram()");
    process.exit(1);
  }

  const program = mod.buildProgram();
  const areas = visibleSubcommands(program).sort((a, b) =>
    cmdName(a).localeCompare(cmdName(b))
  );

  // Clean only generated pages (preserve _examples/)
  if (existsSync(OUT_DIR)) {
    for (const f of readdirSync(OUT_DIR)) {
      if (f.endsWith(".md")) rmSync(join(OUT_DIR, f));
    }
  }
  mkdirSync(OUT_DIR, { recursive: true });

  let count = 0;
  for (const area of areas) {
    const name = cmdName(area);
    const page = renderAreaPage(area, areas.map(cmdName));
    writeFileSync(join(OUT_DIR, `${name}.md`), page + "\n");
    count++;
  }

  writeFileSync(join(OUT_DIR, "README.md"), renderIndex(areas, program) + "\n");

  console.log(`✔ ${count} command man pages generated in docs/commands/ (+ index)`);
}

main().catch((e) => {
  console.error("✖ build-docs failed:", e);
  process.exit(1);
});
